In [6]:
import os
import numpy as np
import pandas as pd
import csv
from sklearn import tree
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from scipy.stats import uniform, norm
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE

In [7]:
x_train = np.empty((0,5))
y_train = np.array([])

with open("Toy Dataset.csv","r") as f:
    d_reader = csv.reader(f,delimiter=",",quotechar="\"")
    first = True
    
    for line in d_reader:
        if first:
            first = False
            continue
        x_train = np.append(x_train,np.array(list(map(int,line[2:7]))).reshape((1,5)),axis=0)
        y_train = np.append(y_train,int(line[8]))
print(x_train.shape)
print(y_train.shape)
# print(y_train)

(419, 5)
(419,)


In [8]:
rand_seed = 3454132

oversampler = SMOTE(sampling_strategy="not majority",random_state=rand_seed)

x_train, y_train = oversampler.fit_resample(x_train,y_train)

In [9]:
print(x_train.shape)
print(y_train.shape)


(636, 5)
(636,)


In [14]:
print(x_train,y_train)

[[1. 1. 0. 1. 0.]
 [2. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]
 ...
 [2. 1. 1. 0. 0.]
 [2. 1. 1. 0. 0.]
 [2. 1. 1. 0. 0.]] [4. 5. 4. 1. 2. 4. 3. 3. 3. 1. 1. 4. 4. 1. 4. 4. 1. 1. 4. 4. 3. 6. 4. 3.
 6. 1. 3. 1. 6. 1. 2. 6. 6. 1. 4. 4. 1. 3. 2. 1. 1. 2. 3. 3. 1. 2. 1. 2.
 3. 4. 3. 3. 2. 6. 3. 6. 1. 4. 2. 2. 1. 5. 2. 1. 4. 1. 1. 2. 1. 4. 1. 4.
 2. 1. 4. 1. 6. 1. 1. 3. 5. 1. 1. 6. 4. 4. 4. 1. 4. 1. 1. 4. 6. 4. 4. 4.
 6. 3. 2. 1. 6. 1. 6. 1. 4. 5. 1. 2. 6. 5. 2. 1. 1. 4. 1. 1. 2. 3. 6. 1.
 2. 5. 4. 1. 1. 4. 2. 4. 4. 4. 4. 2. 1. 3. 6. 1. 5. 6. 5. 5. 4. 2. 3. 3.
 5. 2. 6. 2. 1. 4. 3. 2. 5. 1. 3. 3. 4. 2. 2. 4. 3. 2. 2. 4. 1. 5. 4. 3.
 4. 2. 4. 3. 6. 3. 4. 4. 3. 4. 1. 6. 1. 3. 4. 5. 6. 3. 2. 1. 1. 3. 1. 6.
 6. 1. 5. 3. 1. 1. 2. 3. 6. 3. 4. 1. 1. 3. 3. 1. 2. 1. 1. 4. 1. 3. 5. 1.
 6. 3. 3. 2. 4. 2. 2. 4. 1. 4. 4. 4. 2. 3. 2. 5. 4. 1. 4. 2. 1. 4. 3. 4.
 1. 1. 5. 3. 2. 3. 1. 5. 6. 4. 2. 3. 1. 3. 5. 4. 4. 4. 4. 4. 2. 2. 6. 1.
 1. 1. 1. 5. 6. 3. 5. 5. 6. 2. 1. 1. 4. 1. 1. 5. 3. 6. 2. 2. 5. 4. 1. 2.
 4. 6. 4. 

In [13]:
freq = {}
for i in y_train:
    if i not in freq:
        freq[i] = 0
    freq[i] += 1
for k,v in freq.items():
    print("{} {}".format(k,v))

4.0 106
5.0 106
1.0 106
2.0 106
3.0 106
6.0 106
