In [1]:
import os
import numpy as np
import pandas as pd
import csv
from csv import reader
from csv import writer
import custom_models as cm
from sklearn import tree
from scipy.stats import uniform, norm
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE, RandomOverSampler
from sklearn.feature_selection import SelectFromModel, SelectKBest, VarianceThreshold, chi2, f_classif, mutual_info_classif
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from XLB import *
import xlb_hyperparamsearch as xlbh
from apyori import apriori
from sklearn.metrics import f1_score

import warnings
warnings.filterwarnings('ignore')

In [2]:
# extract data from files
x_train, y_train = extract_data("FinalTrainingSet.csv")
x_val, y_val = extract_data("Validation Set.csv")

# scale data values
scaler = MinMaxScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_val = scaler.transform(x_val)

# feature selection
num_features = 69
feat_sel = VarianceThreshold()
x_train = feat_sel.fit_transform(x_train)
feat_sel_2 = SelectKBest(chi2,k=num_features)
x_train = feat_sel_2.fit_transform(x_train,y_train)
# print(feat_sel_2.get_support())
x_val = feat_sel_2.transform(feat_sel.transform(x_val))

rand_seed = 3454132

oversampler = SMOTE(sampling_strategy="not majority",random_state=rand_seed)
x_smote, y_smote = oversampler.fit_resample(x_train,y_train)
# print(x_smote.shape,y_smote.shape)

oversampler = RandomOverSampler(sampling_strategy="not majority",random_state=rand_seed)
x_os, y_os = oversampler.fit_resample(x_train,y_train)
# print(x_os.shape,y_os.shape)

In [3]:
#MOVING FEATURE HEADERS INTO A LIST
import csv

f = open("FinalTrainingSet.csv")
reader = csv.reader(f)
features = next(reader)
row = list(reader)

csv_temp = pd.read_csv("FinalTrainingSet.csv")
Theme_numbered = csv_temp['Theme(Numbered)'].tolist()
Theme_numbered = np.asarray(Theme_numbered) 

# print(Theme_numbered.shape)
# x_train = np.append(x_train, Theme_numbered.reshape(Theme_numbered.shape[0], 1), axis=1)
# print(x_train.shape)

# x_train = np.delete(x_train, 69, axis=1)

#Deleting everything except features from the dataset
features.remove("Row Labels")
features.remove("Theme")
features.remove("Theme(Numbered)")
# print(len(features))
#Retained features after selection
selected_feats = feat_sel_2.get_support(True)

for ind, ft in sorted(enumerate(features), reverse=True): 
    if ind not in selected_feats:
        del features[ind]  
        
# np.append(x_train, Theme_numbered)
features.append('Theme_numbered')

new_column = pd.DataFrame({'Theme_numbered': Theme_numbered}) 
csv_temp = csv_temp.merge(new_column, left_index = True, right_index = True)

column = csv_temp.Theme_numbered

# print(features)
row_count = len(row)
f.close()
 
# print(x_train.shape)

In [4]:
emotions = ["IsCalm", "IsCheerful", "IsBravery", "IsFearful", "IsLove", "IsSadness"]
label_supp = [0.3117,  0.1372, 0.1397,  0.2469, 0.0673, 0.0973]
    
for theme in range(1,7):
    verbose = False
    num_folds = 5
    model = cm.APyoriAdapter(params={})
    targ_supp = [1 - label_supp[theme - 1],label_supp[theme - 1]]
    parameters = {
        "num_features" : 69,
        "thresh_mean" : 0.5,
        "thresh_std" : 0.15,
        "min_support_lo" : 0.16,
        "min_support_hi" : 0.22,
#         "min_confidence_lo" : 0.036,
#         "min_confidence_hi" : 0.539,
        "min_confidence_lo" : 0.00,
        "min_confidence_hi" : 0.00,
        "col_names" : features[:-1],
        "label_names" : ["IsNot{}".format(emotions[theme-1][2:]),emotions[theme - 1]],
        "label_support" : targ_supp,
        "min_rules_lo" : 5,
        "min_rules_hi" : 20
    }
    y_targ = np.reshape(np.array([y_smote == theme]),(750,))
    hyperparams, result, model = xlbh.hyperparameter_search(
        num_folds=num_folds,model=model,parameters=parameters,X=x_smote,\
        y=y_targ,\
        verbose=True, num_iter=200,interval=10,random_state=69420
    )
    
    with open("rules{}.txt".format(emotions[theme - 1]),"w") as fOut:
        ruleset = model.ruleset
        fOut.write("{}\n".format("\n\n".join([x.__str__() for x in ruleset])))
        print("Average Interestingness: {:.2f}".format(model.evaluate()))
        probas = model.predict_proba(x_val)
        labels = model.predict(x_val)
        acc = model.score(x_val,y_val == theme)
        print("Stats for {}".format(emotions[theme - 1]))
#         print(probas)
#         print(labels,y_val == theme)
        print("Accuracy: {:.2f}".format(acc))
        print("F1-score: {}".format(f1_score(
            labels,list(map(int,y_val == theme))
        )))

Iteration 5 / 10
Best Result: 0.05
Iteration 10 / 10
Best Result: 0.06
Average Interestingness: 0.06
Stats for IsCalm
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [ True  True  True  True False False False False False False False False
 False False False False False False False False False]
Accuracy: 0.81
F1-score: 0.0
Iteration 5 / 10
Best Result: 0.09
Iteration 10 / 10
Best Result: 0.10
Average Interestingness: 0.11
Stats for IsCheerful
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [False False False False  True  True  True False False False False False
 False False False False False False False False False]
Accuracy: 0.86
F1-score: 0.0
Iteration 5 / 10
Best Result: 0.09
Iteration 10 / 10
Best Result: 0.09
Average Interestingness: 0.11
Stats for IsBravery
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [False False False False False False False  True  True  True  True False
 False False False False False False False False False]
Accuracy: 0.81
F1-score: 0.0
Iteration 5 / 10
Best Result: 0.0

In [6]:
for k,v in hyperparams.items():
    print("{} -> {}".format(k,v))

thresholds -> [0.47451572 0.40118617 0.3669801  0.49732092 0.37064738 0.50284855
 0.26639129 0.36131771 0.6211239  0.45110467 0.53024349 0.31763788
 0.32978629 0.45909122 0.6227482  0.1941278  0.56800976 0.318423
 0.39597653 0.54094139 0.41534273 0.61843739 0.71562743 0.45629711
 0.46138987 0.22634265 0.52701838 0.5872876  0.42918885 0.5904915
 0.71482511 0.40857648 0.46642116 0.44597248 0.59242758 0.54962625
 0.2173277  0.5717978  0.4793687  0.37434666 0.70458894 0.64757908
 0.57584678 0.19112088 0.59150198 0.54743306 0.47402216 0.52099661
 0.52416071 0.5529033  0.49319975 0.51837527 0.73512309 0.39287433
 0.47129881 0.61111037 0.62961304 0.52383199 0.77117974 0.21046687
 0.43351816 0.36758352 0.6450635  0.4305435  0.52657623 0.64916476
 0.452944   0.36659421 0.44683703]
min_support -> 0.2022197075052909
min_confidence -> 0.0
col_names -> ['Tempo', 'Arousal', 'IsMajor', 'IsMinor', 'IsDissonant', 'Derivative of Root Mean Square Overall Standard Deviation', 'Derivative of Running Mean o